#!/usr/bin/env bash

if clang++ -v
then
    CC=clang++
else
    CC=g++
fi

${CC} \
-std=c++20 \
./src/sorth.cpp \
./src/interpreter.cpp \
./src/builtin_words.cpp \
./src/location.cpp \
./src/error.cpp \
./src/source_buffer.cpp \
./src/tokenize.cpp \
./src/dictionary.cpp \
./src/operation_code.cpp \
./src/value.cpp \
./src/array.cpp \
./src/byte_buffer.cpp \
./src/data_object.cpp \
./src/hash_table.cpp \
./src/code_constructor.cpp \
./src/terminal_words.cpp \
./src/posix_io_words.cpp \
./src/user_words.cpp \
-O3 \
-o sorth && \
strip ./sorth
