#!/usr/bin/env bash


function bundle
{
    echo "Bundling $1 to $2."

    rm -rf $2/*

    mkdir -p $2
    mkdir -p $2/std

    chmod +x $1
    xattr -d com.apple.quarantine $1

    cp ${1} ${2}/sorth$3

    cp ./std.f $2
    cp -r ./std/* $2/std
}


rm -rf ./strange-forth/bin/*

bundle ./package-bin/sorth-aarch64-apple-darwin        ./strange-forth/bin/arm64/darwin/
bundle ./package-bin/sorth-x86_64-apple-darwin         ./strange-forth/bin/x64/darwin/
bundle ./package-bin/sorth-arm-unknown-linux-gnu       ./strange-forth/bin/arm64/linux/
bundle ./package-bin/sorth-x86_64-unknown-linux-gnu    ./strange-forth/bin/x64/linux/
bundle ./package-bin/sorth-x86_64-pc-windows-msvc.exe  ./strange-forth/bin/x64/win32/ ".exe"


pushd strange-forth

vsce package

popd
