#!/usr/bin/env bash


echo "Launching dev server"
shift


PLATFORM=$1
ARCH=$2

shift
shift


echo "Running under ${PLATFORM} on ${ARCH}."
exec ../build/sorth ../strange-forth/server/language_server.f $@
