#!/usr/bin/env bash


FILE_NAME=sorth_lsp_log.txt


echo "Launching dev server" > $FILE_NAME
shift


PLATFORM=$1
ARCH=$2

shift
shift


echo "Running under ${PLATFORM} on ${ARCH}." &>> $FILE_NAME
exec ../build/sorth ../strange-forth/server/language_server.f $@ &>> $FILE_NAME
