#!/usr/bin/env bash

FILE_NAME=sorth_lsp_log.txt


echo "Launching server"

shift

PLATFORM=$1
ARCH=$2

shift
shift

echo "Server launching with: ${PLATFORM}--${ARCH}"


exec ./bin/${ARCH}/${PLATFORM}/sorth server/language_server.f $@
